version: "3.6"
services:
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_DATABASE: movie_trivia
      MYSQL_USER: trivia
      MYSQL_PASSWORD: 8BVDOE4PRwOne8l7c6FZmAeg
      MYSQL_ROOT_PASSWORD: sviEMo3Hz3NoqfUC0oZHEOZz
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    expose:
      - 3600
    healthcheck:
      test: ["CMD", "mysqlshow"]
      interval: 5m
      timeout: 15s
      retries: 3
    image: mysql:5.7
    networks:
      - back_tier
    restart: always
    volumes:
      - ./db-data:/docker-entrypoint-initdb.d
  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      - front_tier
    restart: on-failure
    volumes:
      - ./movie-trivia-game:/var/www/movie-trivia-game
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    environment:
      VIRTUAL_HOST: movie-trivia.noondaysun.org
    ports:
      - 80:80
  php74:
    container_name: php74
    build:
      context: .
    expose:
      - 9000
    networks:
      - back_tier
      - front_tier
    restart: on-failure
    volumes:
      - ./movie-trivia-game:/var/www/movie-trivia-game
    working_dir: /var/www/movie-trivia-game
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - back_tier
    restart: on-failure

networks:
  front_tier:
  back_tier:
